//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetTopologySuite.IO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetTopologySuite.IO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When writing a SQL Server geography value, the holes of a polygon must be oriented clockwise..
        /// </summary>
        internal static string InvalidGeographyHoleOrientation {
            get {
                return ResourceManager.GetString("InvalidGeographyHoleOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When writing a SQL Server geography value, the shell of a polygon must be oriented counter-clockwise. To write polygons without a shell, set SkipGeographyChecks..
        /// </summary>
        internal static string InvalidGeographyShellOrientation {
            get {
                return ResourceManager.GetString("InvalidGeographyShellOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GEOGRAPHY structure received is incomplete and cannot be read..
        /// </summary>
        internal static string UnexpectedEndOfStream {
            get {
                return ResourceManager.GetString("UnexpectedEndOfStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type: {0}.
        /// </summary>
        internal static string UnexpectedGeographyType {
            get {
                return ResourceManager.GetString("UnexpectedGeographyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} of the GEOGRAPHY structure received. This version isn&apos;t supported..
        /// </summary>
        internal static string UnexpectedGeographyVersion {
            get {
                return ResourceManager.GetString("UnexpectedGeographyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Geometry implementation: {0}.
        /// </summary>
        internal static string UnexpectedGeometryType {
            get {
                return ResourceManager.GetString("UnexpectedGeometryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type: {0}.
        /// </summary>
        internal static string UnexpectedOgcGeometryType {
            get {
                return ResourceManager.GetString("UnexpectedOgcGeometryType", resourceCulture);
            }
        }
    }
}
